extends: 
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins: 
  - '@typescript-eslint'
root: true
parserOptions:
  project: './tsconfig.json'
rules:
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - argsIgnorePattern: "^_"
